[project]
name = "bench_utils"
version = "0.1.2.dev4"
description = "Simple module for benchmarking"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.0",
    "scikit-learn>=1.7.0",
    "scipy>=1.15.3",
]
authors = [
    {name = "Anton Shiryaev", email = "med.phisiker@gmail.com"}
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["bench_utils"]

[project.urls]
Repository = "https://github.com/VLMHyperBenchTeam/bench_utils"
Homepage = "https://github.com/VLMHyperBenchTeam"
