[project]
name = "bench-utils"
version = "0.1.2.dev2"
description = "Utilities for benchmarking VLM HyperBench models"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.0",
    "scikit-learn>=1.7.0",
    "scipy>=1.15.3",
    "model-interface",
]
authors = [
   {name = "VLMHyperBenchTeam", email = "contact@vlmhyperbench.team"},
   {name = "Anton Shiryaev", email = "med.phisiker@gmail.com"}
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["bench_utils"]

[tool.uv.sources]
model-interface = { workspace = true }
