[project]
name = "bench_utils"
version = "0.1.0"
description = "Simple module for benchmarking"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.0",
    "scikit-learn>=1.7.0",
    "scipy>=1.15.3",
]

[build-system]
requires = [
    "setuptools>=77",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["bench_utils"]
